services:
  redis-master:
    image: redis:7.2
    container_name: redis-master
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      - redis-net

  redis-replica-1:
    image: redis:7.2
    container_name: redis-replica-1
    ports:
      - "6380:6379"
    command: redis-server --replicaof redis-master 6379
    depends_on:
      - redis-master
    networks:
      - redis-net

  redis-replica-2:
    image: redis:7.2
    container_name: redis-replica-2
    ports:
      - "6381:6379"
    command: redis-server --replicaof redis-master 6379
    depends_on:
      - redis-master
    networks:
      - redis-net

  redis-replica-3:
    image: redis:7.2
    container_name: redis-replica-3
    ports:
      - "6382:6379"
    command: redis-server --replicaof redis-master 6379
    depends_on:
      - redis-master
    networks:
      - redis-net

  redis-replica-4:
    image: redis:7.2
    container_name: redis-replica-4
    ports:
      - "6383:6379"
    command: redis-server --replicaof redis-master 6379
    depends_on:
      - redis-master
    networks:
      - redis-net

  redis-sentinel-1:
    image: redis:7.2
    container_name: redis-sentinel-1
    ports:
      - "26379:26379"
    command: redis-sentinel /etc/redis/sentinel.conf
    volumes:
      - ./sentinel/redis-sentinel.conf:/etc/redis/sentinel.conf
    depends_on:
      - redis-master
    networks:
      - redis-net

  redis-sentinel-2:
    image: redis:7.2
    container_name: redis-sentinel-2
    ports:
      - "26380:26379"
    command: redis-sentinel /etc/redis/sentinel.conf
    volumes:
      - ./sentinel/redis-sentinel.conf:/etc/redis/sentinel.conf
    depends_on:
      - redis-master
    networks:
      - redis-net

  redis-sentinel-3:
    image: redis:7.2
    container_name: redis-sentinel-3
    ports:
      - "26381:26379"
    command: redis-sentinel /etc/redis/sentinel.conf
    volumes:
      - ./sentinel/redis-sentinel.conf:/etc/redis/sentinel.conf
    depends_on:
      - redis-master
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge